smackers/smack

bin/build-linux-cmake.sh, bin/build-linux.sh
I noticed this flag was missing from a few of the commands. Adding this argument will allow building without interactivity.
=> Added '-y' flag to the command 'add-apt-repository'. 

README.md
Added Jenkins build status icon.
=> Added Jenkins Build Status Icon

.gitignore, Doxyfile
For more information on how to document, please read this: http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html
=> Added Doxygen configuration file for generating documentation. 

bin/smack.py, bin/svcomp_filters.py
=> Add bv-vector classifier

bin/smack.py
- Fix issues with run http://pc352.emulab.net/results.py?category=HeapManipulation&--verifier=svcomp&Submit=Submit
- Need discussion on creating temporary files
=> Fix link error by renaming defined exit functions

share/smack/include/pthread.h, share/smack/lib/pthread.c, test/pthread/equal.c, test/pthread/equal2.c
Z - the code changes are minor, but I thought I'd give you a chance to review my commit messages, to make sure they're up to snuff.  ;)
-M
=> Pthread equal

share/smack/lib/smack.c
Fix a couple of floating point functions
=> Minor floating point fixes

share/smack/lib/smack.c, share/smack/svcomp/utils.py
Revert the still non-working remainder function and fix error with float-no-simp4_true-unreach-call.i
=> Float fixes

.travis.yml, README.md, bin/build.sh, test/config.yml, test/regtest.py
Implemented support for Travis CI. We are switching from Jenkins since we do not need support for multiple platforms any more, and also Travis integrates nicely with Github.
=> Travis CI support

share/smack/top.py, test/basic/transform-bpl.c, test/basic/transform-out.c, test/regtest.py
* for generated Boogie code via --transform-bpl
* for verifier output via --transform-out
=> Plugin transformations.

include/dsa/DSNode.h, include/smack/AddTiming.h, include/smack/BoogieAst.h, include/smack/BplFilePrinter.h, include/smack/BplPrinter.h, include/smack/Contracts.h, include/smack/DSAWrapper.h, include/smack/Regions.h, include/smack/Slicing.h, include/smack/SmackInstGenerator.h, include/smack/SmackModuleGenerator.h, include/smack/SmackRep.h, lib/smack/BoogieAst.cpp, lib/smack/BplFilePrinter.cpp, lib/smack/BplPrinter.cpp, lib/smack/DSAWrapper.cpp, lib/smack/Regions.cpp, lib/smack/SmackInstGenerator.cpp, lib/smack/SmackModuleGenerator.cpp, lib/smack/SmackRep.cpp, tools/llvm2bpl/llvm2bpl.cpp
* Allows faster recompilation.
=> Untangling include dependencies.

test/basic/func_ptr_alias.c, test/basic/func_ptr_alias1.c, test/basic/func_ptr_alias1_fail.c, test/basic/func_ptr_alias_fail.c
=> Avoid problematic alias annotation on OSX

include/smack/DSAWrapper.h, lib/smack/DSAWrapper.cpp, lib/smack/Regions.cpp, test/basic/struct_alias.c, test/basic/struct_alias_fail.c
* when some equivalent DSA nodes have distinct collapsed status
* fixes #258
=> Fix unsound region splitting.

include/smack/Naming.h, lib/smack/Naming.cpp, lib/smack/SmackRep.cpp
Necessary for objective-c support
=> Add support for llvm unnamed variables

lib/smack/BoogieAst.cpp
=> Avoid precedence confusion with conditional expression.

share/smack/frontend.py, share/smack/top.py
Helps with backwards-compatibility,
in particular for svcomp
Fixes #364
=> Make Language Struct lowercase

include/smack/Naming.h, lib/smack/Naming.cpp, lib/smack/SmackInstGenerator.cpp
This fixes setting the entry point for Rust program.
=> Rust entry point fix

share/smack/svcomp/toSVCOMPformat.py, share/smack/top.py
This PR attempts to fix imprecise witness generation logic. Now the violation node should be the call site of last function called in the source file.
=> Witness generation fixes for SV-COMP

include/smack/SmackRep.h, lib/smack/SmackRep.cpp, share/smack/lib/smack.c
I am running SVCOMP to see if this has any effect on performance. We could maybe review it in the meantime.
=> Fixed layout of external memory

lib/smack/IntegerOverflowChecker.cpp, share/smack/frontend.py
This PR address the issue #428.
@zvonimir I wanted to add some regressions but wasn't quite sure where to put them.
=> Leverage UBSan instead of ftrapv for integer overflow checking

share/smack/top.py
This PR re-formats the Corral error traces as follows,
1. Ignore calls to SMACK internal functions such as `__SMACK_static_init` and `$alloc`.
2. Remove parentheses around descriptions such as `(a  = 1)` -> `a = 1`.
3. Print bit-vector values as unsigned long (e.g., `a = 1bv32` to `a = 1UL`).
4. Print floating-point values in the Python format. (e.g., `a = 0x08.000000e-1f24e8` to `a = 0.5`)
I think we can improve the error traces as follows,
1. Remove error trace lines in `smack.c`.
2. Restructure SMACK output like the following,
```
SMACK found an assertion failure in test.c (5,3).
Execution trace:
...
```
=> Better error traces

lib/smack/Prelude.cpp, test/c/basic/srem.c, test/c/basic/srem_fail.c, test/c/basic/urem.c, test/c/basic/urem_fail.c
=> Model C integer remainder operations

lib/smack/Prelude.cpp
=> Inline `isExternal`

.travis.yml, bin/build.sh, bin/smack, bin/smack-doctor, bin/vsmack, docs/installation.md, format/run-clang-format.py, share/smack/doctor.py, share/smack/frontend.py, share/smack/reach.py, share/smack/replay.py, share/smack/svcomp/filters.py, share/smack/svcomp/random_testing.py, share/smack/svcomp/toSVCOMPformat.py, share/smack/svcomp/utils.py, share/smack/top.py, share/smack/utils.py, test/c/reach/regtest.py, test/regtest.py
This mostly boiled down to simple syntax updates.
I also updated our installation documentation.
=> Upgraded to Python 3

test/c/basic/sign_cast.c, test/c/basic/sign_cast_fail.c, test/c/bits/pack_struct.c, test/c/bits/pack_struct_fail.c
This PR adds the regressions needed when we cleaned up the issues.
=> Add missing regressions

share/smack/include/bits/pthreadtypes.h, share/smack/include/bits/types/struct_timespec.h, share/smack/include/pthread.h, share/smack/include/smack.h, share/smack/lib/pthread.c, share/smack/lib/smack.c
I think this now completes it.
Closes #505
=> Added missing pthread header functions and types

include/smack/SmackRep.h, lib/smack/SmackInstGenerator.cpp, lib/smack/SmackRep.cpp
=> Add support for `SelectConstantExpr`

lib/smack/DSAWrapper.cpp, test/c/bits/test_memset.c, test/c/bits/test_memset_fail.c
=> Mark MemOpd nodes type-unsafe

share/smack/frontend.py, share/smack/top.py, test/c/bits/left_shift_negative_fail.c, test/c/bits/left_shift_overflow.c, test/c/bits/left_shift_overflow_fail.c, test/c/bits/left_shift_unsigned.c, test/c/bits/left_shift_unsigned_fail.c, test/c/memory-safety/config.yml, test/c/pthread/join_null_retval.c, test/c/strings/strcat_overflow.c, test/c/strings/strcpy_overflow.c, test/rust/basic/add_overflow.rs, test/rust/basic/mul_overflow.rs, test/rust/basic/sub_overflow.rs
This cleans up the interaction between checking of various
properties. A user can select all properties they would like
for SMACK to check on their code.
=> Implemented check option for selecting properties to check

.travis.yml, include/smack/Naming.h, include/smack/SmackOptions.h, lib/smack/Naming.cpp, lib/smack/SmackInstGenerator.cpp, lib/smack/SmackOptions.cpp, share/smack/top.py, test/regtest.py, test/rust/panic/core_panic_fail.rs, test/rust/panic/core_panic_fmt_fail.rs, test/rust/panic/std_panic.rs, test/rust/panic/std_panic_fail.rs, test/rust/panic/std_panic_fmt_fail.rs
This improves detection and handling of panics arising in Rust programs.
=> Improve Rust panics

share/smack/top.py, test/regtest.py, test/rust/panic/config.yml, test/rust/panic/core_panic_fail.rs, test/rust/panic/core_panic_fmt_fail.rs, test/rust/panic/std_panic_fail.rs, test/rust/panic/std_panic_fmt_fail.rs
This adds status codes to smack's verification reporting.
=> Add exit codes

lib/smack/Naming.cpp
=> Add missing panic

share/smack/svcomp/utils.py, share/smack/top.py
=> Fix SV-COMP scripts

lib/smack/SmackWarnings.cpp
=> Fixing discrepancy between bit-vector flag in llvm2bpl and Python script

share/smack/include/string.h, share/smack/lib/string.c, test/c/strings/test_memcmp.c, test/c/strings/test_memcmp_fail.c
I implemented it using a loop, which then has to be unrolled an
appropriate amount of times. This could be improved if we want
to use quantifiers, but I think this should be good for now.
Closes #629
=> Implemented modeling of memcmp

lib/smack/IntegerOverflowChecker.cpp
We used to assume two extractvalue instructions that use the overflow checking
intrinsics are consecutive, which may not be the case. This commit remove the
reliance on this assumption.
=> Fixed incorrect reliance on instruction order for overflow checking

share/smack/errtrace.py, share/smack/svcomp/toSVCOMPformat.py, share/smack/svcomp/utils.py, share/smack/top.py
=> Fix error witness generation

share/smack/utils.py
=> Do not add spaces after each line read from stdout

.github/workflows/smack-ci.yaml, bin/build.sh
=> Removed the occurrences of `TRAVIS` in bin/build.sh

lib/smack/RustFixes.cpp
This improves matching for Rust function names by requiring they match the syntax of Rust hashed function names or requiring an exact match.
=> Fix name matching for Rust functions

include/smack/SmackRep.h, lib/smack/SmackRep.cpp
=> Add allocation size attribute for global variables

lib/smack/ExtractContracts.cpp
=> Fix a undefined behavior in `ExtractContracts.cpp`

CMakeLists.txt, share/smack/include/cassert
=> Added cassert C++ header
