- bin/build.sh
The Boogie build process needs sudo privilege to install NUnit.
> Fixed NUnit installation for the Boogie build process.

- bin/boogie
- bin/corral
the script is quoted. Previously if parameters with spaces in were passed to the script
then those parameters would be split into separate parameters.
E.g.
./boogie "my silly file name with spaces in it.bpl"
will expand to
/path/to/Boogie.exe "my" "silly" "file" "name" "with" "spaces" "in"
"it.bpl"
when invoked which would most likely fail.
> Fix Boogie and Corral wrapper scripts so that each argument passed to

- bin/build.sh
* Delete /tmp/nuget/ after it gets created and used by 'mono nuget.exe' - if sudo user installs first and this folder isn't deleted, subsequent local, non-sudo installs can't write to this directory.
* Add --prefix INSTAlLDIR/bin to $PATH as first item, not last, so local installations get preference over system-wide installations
* Trim trailing '/' characters from --prefix argument values, to prevent seeing '//' in smack.environment
> Small fixes to build.sh

- test/regtest.py
I overlooked this function call when I added the multi-threading support. This patches the problem.
> Fixed missing @expect logging.

- bin/build.sh
- test/regtest.py
Before these changes Jenkins reported builds as successful even if there were tests
that timed out/failed. This fixes that issue by setting the shell return status
based on the results of the regressions tests. Jenkins will now report a build as
failed if the shell return status is anything other than 0.
> Modified the build and test scripts so that test failures are reported.

- bin/smack.py
Fixes various references that were being made without prior assignment.
This commit initializes variables that were being referenced but not initialized. This issue was causing various SVCOMP benchmarks to fail.
Closes-Bug: #132
> Fixes referencing issues in function smackdOutput in Smack.py

- share/smack/include/smack.h
- share/smack/lib/smack.c
They cause some tests to fail and are currently unnecessary.
> Removed long double function signatures

- CMakeLists.txt
CMakeLists now searches for llvm-config-3.7 first (which is different from llvm-config).
> Simplifying build on Ubuntu 16.04.

- include/smack/SmackInstGenerator.h
- lib/smack/SmackInstGenerator.cpp
- share/smack/replay.py
- share/smack/top.py
- share/smack/utils.py
This adds the basic capability to check whether counterexamples returned by Corral are executable, by generating a test harness providing the required inputs to the entry-point procedure, and stubs providing the required return values from special procedures like `__VERIFIER_nondet_int`. This is turned on with a single `--replay` flag.
> Error replay

- bin/build.sh
Specifically, reduce early-exit due to pre-existing dependency local repo or executable link.
> Improve build.sh re-runnability

- share/smack/lib/smack.c
- test/memory-safety/malloc_nondet.c
- test/memory-safety/malloc_nondet_fail.c
For some reason when size was negative we used to allocate an
object of size 1. This seems like a hack to me and I am not sure
why it was introduced in the first place. I cleaned this up now
by requiring that size is not negative, and blocking executions
with negative size.
> Added assumption to alloc that size is not negative

- CMakeLists.txt
- include/smack/VerifierCodeMetadata.h
- lib/smack/VerifierCodeMetadata.cpp
- tools/llvm2bpl/llvm2bpl.cpp
Adds metadata annotations in LLVM bitcode to distinguish between “erasable” instructions that pertain only to verification, e.g., values feeding into `assume` and `assert` statements, and regular instructions that will actually be executed in the generated code.
> Adding verifier-code metadata.

- lib/AssistDS/StructReturnToPointer.cpp
- test/basic/struct_const_return.c
- test/basic/struct_const_return_fail.c
Consider the following example,
```LLVM
define { i32, i64 } @foo() {
ret { i32, i64 } { i32 1, i64 2 }
}
```
It triggers an [assertion failure](https://github.com/smackers/smack/blob/master/lib/AssistDS/StructReturnToPointer.cpp#L114). This pull request intends to extend this pass to handle functions returning constant structs. It first allocates a place to hold the struct and then stores the constant into the space. For the example above, the PR converts the function body into the following form,
```LLVM
%1 = alloca { i32, i64 }
%2 = getelementptr { i32, i64 }, { i32, i64 }* %1, i32 0, i32 0
store i32 1, i32* %2
%3 = getelementptr { i32, i64 }, { i32, i64 }* %1, i32 0, i32 1
store i64 2, i64* %3        
%4 = load { i32, i64 }, { i32, i64 }* %1
ret { i32, i64 } %4
```
Note that this PR …
> Add support for constant structs being function returns

- share/smack/include/smack.h
- share/smack/svcomp/utils.py
* Avoid platform-specific `__builtin_*` macros.
* Defining `__builtin_memcpy` as `__builtinx_memcpy` confuses Clang on OSX.
* Fixes #239.
> Limit SVCOMP compiler hacks to SVCOMP frontend.

- share/smack/lib/smack.c
Adds support for the 1-bit integer type for regular integers, and sign extension/truncation for 1-bit bit-vectors. The Rust compiler emits i1 and bv1 (in bv mode) for the boolean type. Other languages may require this feature as well.
> Add support i1 and bv1 for languages that use these types

- include/smack/BoogieAst.h
- lib/smack/BoogieAst.cpp
- lib/smack/SmackInstGenerator.cpp
- test/basic/select.c
- test/basic/select_fail.c
The old encoding translates a select instruction to `havoc(x); assume(c==1==>x==v1 && c!=1==>x==v2);` where `c` is the condition and `v1`, `v2` is true value and false value, respectively.
The new encoding translates it to `x = if c ==1 then v1 else v2`.
This pull request addresses issue #174.
> Rewrite select instruction encoding

- LICENSE
- README.md
- docs/installation.md
This PR updates the links to point to their GitHub repositories instead of Codeplex.
This time for `develop`.
Closes #280
> Update Boogie and Corral links

- include/smack/SmackInstGenerator.h
- lib/smack/SmackInstGenerator.cpp
Currently SMACK doesn't emit record procedures for function arguments.  The `llvm.dbg.value` calls corresponding to function arguments are in the beginning of the entry block in a function. Source location annotations are not generated for these call instructions which must precede record procedure calls in order for them to work. This PR adds source location of the first non-debug instruction to the beginning of each block created.
Then values of non pointer function arguments will be printed as `function-name`:`arg`:`argument-name`.
> Add support for recording function argument values

- share/smack/include/smack.h
- share/smack/lib/smack.c
- share/smack/top.py
Currently, when SMACK runs on a C++ file, clang fails with issues in smack.h and smack.c. This fixes them, and changes the command in top.py from `clang` to `clang++`.
Depends on #283
> Fix C++ boolean header issues

- share/smack/lib/smack.f90
- share/smack/top.py
Add top.py support for using smack on Fortran files 
SMACK exposes two functions to fortran: a raw __verifier_assert() which takes an integer, and assert() which takes a LOGICAL type.
> Fortran support

- CMakeLists.txt
- include/smack/NormalizeLoops.h
- lib/smack/NormalizeLoops.cpp
- tools/llvm2bpl/llvm2bpl.cpp
This adds an LLVM pass to fix #314.
Specifically, if a phi node in a loop header gets its value from a block in the loop body, and the source block branches when terminating, the generated Boogie code incorrectly updates the variable corresponding to the phi node.  To fix this, a forwarding block is added between the source block and the header. The generated Boogie code then updates the value for the phi node in the forwarding block, and other destination blocks keep the non-updated value for the phi node. Loops of this form are usually generated when compiling with optimization.
> Fix phi nodes that get their values from a loop body

- include/smack/MemorySafetyChecker.h
- lib/smack/MemorySafetyChecker.cpp
- share/smack/include/smack.h
- share/smack/lib/smack.c
Attempting to salvage a possibly outdated fix for Issue #197 to avoid region collapse due to memory safety checking.
> Avoid mem safety region collapse

- lib/smack/Naming.cpp
Extend Naming::escape's functionality
to escape many more characters.
Because Boogie can't handle backslashes in
identifiers, the call to llvm::DOT::EscapeString
has been removed. All of the characters that this
method currently escapes have been added to
Naming::escape
Most characters are replaced with underscores.
Theoretically, this could cause naming conflicts
in the future, but the probablity of two names
being identical except for their special characters
is low enough that it's worth it to neglect that
possibility right now.
Fixes #323
> Make escape characters more robust

- share/smack/lib/math.c
The math.c functions were not passing an rmode variable to the dtf and ftd functions.
> Fixed dtf and ftd calls in math.c

- share/smack/include/fenv.h
- share/smack/lib/fenv.c
- test/float/change_rm.c
- test/float/get_rm_invalid.c
- test/float/get_rm_invalid_fail.c
- test/float/set_rm_invalid.c
- test/float/set_rm_invalid_fail.c
- test/mathc/lrint.c
- test/mathc/lrint_fail.c
- test/mathc/lrintf.c
- test/mathc/lrintf_fail.c
- test/mathc/nearbyint.c
- test/mathc/nearbyint_fail.c
- test/mathc/nearbyintf.c
- test/mathc/nearbyintf_fail.c
- test/mathc/rint.c
- test/mathc/rint_fail.c
- test/mathc/rintf.c
- test/mathc/rintf_fail.c
This pull request:
-Redefines rounding mode macros to have values more consistent with
those used by other implementations
-Combines FE_TONEARESTEVEN and FE_TONEARESTAWAY into FE_TONEAREST in
order to conform to the C standard
> Changed definition of rounding modes

- lib/smack/SmackRep.cpp
- test/float/double_to_int.c
- test/float/double_to_int_fail.c
This changes fp2si and fp2ui to always use RTZ as the rounding mode so that
casting from floating-point types to integer types is modeled correctly.
> Fixed fp2si and fp2ui function arguments

- share/smack/top.py
When the input C program is not syntactically correct, SMACK redirects
Clang's output to stdout. However, the message is not colorized, which
can make debugging cumbersome as it's hard to quickly identify the errors.
This commit solves this problem by adding a special flag to Clang such that
the output is colorized if SMACK's output is a tty device, otherwise it is
disabled to avoid annoying color information printed in a file.
> Colorize Clang's output

- share/smack/include/math/math.h
- share/smack/lib/math.c
This pull request:
-Changes the names of the __isfinite and __isfinitef functions to
__finite and __finitef, respectively, in order to be consistent with the
C standard
-Adds several macros specified in the C standard
> Fixes to math.h functions/macros

- share/smack/lib/math.c
This pull request:
-Fixes error in modff function where $fsub.bvdouble was being called
instead of $fsub.bvfloat
-Removes unnecessary call to __VERIFIER_nondet_double() in modff and
modf
> Fixes to modff and modf functions in math.h

- test/basic/uninterpreted.c
- test/basic/uninterpreted_fail.c
Inspired by a question asked by Nathan Chong, I thought it would be nice to share and preserve this recipe for functions which are _uninterpreted_ in the logical sense, in that a given call `f(x)` may return any value, but for `x == y` we are guaranteed that `f(x) == f(y)`.
> Added test for uninterpreted functions.

- bin/smack
- bin/smack-doctor
- bin/vsmack
- share/smack/doctor.py
- share/smack/reach.py
- share/smack/svcomp/toSVCOMPformat.py
- svcomp/bench/src/SMACKBench.py
- svcomp/bench/src/checkWitnesses.py
- svcomp/bench/src/data/index.py
- svcomp/bench/src/data/results.py
- test/reach/regtest.py
- test/regtest.py
Smack only works with Python version 2. On systems where version 3 is the default, Smack can still work simply by specifying `python2` as the interpreter.
> Compatibility with Python-3-default systems.

- share/smack/frontend.py
- share/smack/svcomp/utils.py
Update the svcomp frontend to work
with the new cross-language structure
This includes
-- importing fronend.py as well as top.py
-- getting rid of a circular import in frontend.py
-- changing the svcomp frontend to use new functions
> Quick fixes for svcomp frontend

- share/smack/frontend.py
- share/smack/lib/smack.rs
This adds the front end and libraries for Rust support. The biggest thing that I think needs to be looked at is the way the `smack.rs` library is included (lines 221-231 in `frontend.py`). A directory named `smack` is created where the test file is, and a symbolic link to smack's `smack.rs` is placed there. This is needed to enable the ability to compile the program normally and still have it be verifiable by SMACK.
> Rust frontend

- share/smack/svcomp/toSVCOMPformat.py
- share/smack/svcomp/utils.py
- share/smack/top.py
This commit does the following,
1. Updated SMACK's JSON output generation according to Corral's C
trace format changes.
2. Updated JSON-to-witness-trace translation.
3. Simplified some logic in related scripts.
> Fix SV-COMP witness generation

- include/smack/IntegerOverflowChecker.h
- lib/smack/IntegerOverflowChecker.cpp
- share/smack/frontend.py
- test/bits/left_shift_negative_fail.c
- test/bits/left_shift_overflow.c
- test/bits/left_shift_overflow_fail.c
- test/bits/left_shift_unsigned.c
- test/bits/left_shift_unsigned_fail.c
Changes:
* `--integer-overflow` enables the clang option `-fsanitize=shift`.
* `__ubsan_handle_shift_out_of_bounds` is transformed to assert false with the `overflow` annotation.
* Tests for shifting with a negative negative LHS, left shifting non-negative signed-values, and unsigned values are included.
UBSan does all the work for us to detect undefined left bit shifts. It will check that the shift amount is appropriate for the bit width. For signed left shifts, it performs a right shift of `(bit-width - 1 - left_shift_amt)` bits and checks if this is zero. If it's not zero, then the left shift would shift a `1` past the MSB, which is undefined.
This is meant to fix issue #382.
> Add checking for left-shift overflows in C programs

- share/smack/include/math.h
The macro currently calls __isfinitel, but the function is called __finitel.
> Fixed isfinite() macro

- include/smack/SmackRep.h
- lib/smack/SmackInstGenerator.cpp
- lib/smack/SmackRep.cpp
- share/smack/lib/smack.c
- test/float/bitcast.c
- test/float/bitcast_fail.c
- test/float/float_int_union.c
- test/float/float_int_union_fail.c
Now turning on precise reasoning about floats does not generate
Boogie files with quantifiers.
First, we realized that a bunch of axioms was not needed in the
first place, and so I just removed those.
Second, whenever a cast such as $bitcast.bvfloat.bv32(x) gets
introduced, which happens due to bitcast instructions or stores
into byte maps, I introduce an assume statement such as:
assume ($bitcast.bv32.bvfloat($bitcast.bvfloat.bv32(x)) == x);
This appropriately constrains the uninterpreted
$bitcast.bvfloat.bv32 function.
Closes #412
> Got rid of quantified axioms related to floating-points

- share/smack/lib/math.c
This updates math.c to use type annotations with calls to __SMACK_code, which was added in [this pull request](https://github.com/smackers/smack/pull/435). This results in a simpler implementation for many functions.
> Updated math.c to use new __SMACK_code syntax

- share/smack/lib/smack.rs
As the name suggests, this feature gates the standard Vec class to enable building in no standard Rust programs.
> Enable SMACK to build a no-std Rust crate

- share/smack/lib/smack.c
- test/float/smack_code_annot.c
- test/float/smack_code_annot_fail.c
We don't need functions like `dtf` so I removed them. And floating-point
conversions from/to half-precision numbers are also implemented.
> fix floating-point conversions

- include/smack/SmackRep.h
- lib/smack/Prelude.cpp
- lib/smack/SmackInstGenerator.cpp
- share/smack/lib/smack.c
> enable extractvalue functions when the `--bit-precise` flag is used

- include/smack/SmackInstGenerator.h
- lib/smack/SmackInstGenerator.cpp
- share/smack/frontend.py
- share/smack/lib/intrinsics.c
- test/float/half_intrinsics.c
- test/float/half_intrinsics_fail.c
This adds support for the LLVM conversion intrinsics for converting: `f64`->`f16`,  `f32`->`f16`,  `f16`->`f64` and `f16`->`f32`.
Since the normal mode of LLVM is to use half precision as an IEEE binary16 storage format, this should be all we need for now. (BFloat16 hardware is a ways off apparently.)
Addresses #436.
> Add support for the LLVM half-conversion intrinsics

- test/float/llvm_intrinsic.c
- test/float/llvm_intrinsic_fail.c
This adds a regression for testing an issue with the __finite function that is present with LLVM version 4.0.1. This problem is described further in Issue [#449](https://github.com/smackers/smack/issues/449).
>  Added regression that tests issue with __finite function in LLVM 4.0.1

- lib/smack/IntegerOverflowChecker.cpp
This changes `removeFromParent` to `eraseFromParent` allowing us to remove overflow instructions to avoid a warning generated by the new `visitIntrinsic` code.
> Remove arithmetic overflow intrinsic instructions to prevent an erroneous warning

- include/smack/BoogieAst.h
- lib/smack/BoogieAst.cpp
- lib/smack/SmackInstGenerator.cpp
- test/bits/bitreverse.c
- test/bits/bitreverse_fail.c
- test/bits/byte_swap_fail.c
- test/bits/countlz.c
- test/bits/countlz_fail.c
- test/bits/countlz_fail2.c
- test/bits/countlz_zero_fail.c
- test/bits/countpop32.c
- test/bits/countpop32_fail.c
- test/bits/counttz.c
- test/bits/counttz_fail.c
- test/bits/counttz_fail2.c
This pull request aims to add several of the LLVM bit-wise intrinsics such as count leading zeros.
Optionally, we can add vectorized versions of these operations as well.
I think we should focus on those that have been seen in real programs such as ctlz, and those that are easy to generate the intrinsic through compiler builtins.
This is intended to be merged after the `improve-prelude` pull request since there is some functionality I want to use.
> [WIP] Add LLVM bit intrinsics

- docs/running.md
- docs/usage-notes.md
We have seen a few issues created by users who are not familiar with SMACK's flags. This document intends to provide examples of typical use cases, helping users to enable proper flags for the programs that they are interested in.
> Add some usage notes

- .travis.yml
- lib/smack/Prelude.cpp
- test/bits/pointer_memops.c
- test/bits/pointer_memops_fail.c
This commit fixes the declarations of load/store functions as follows,
1. type-safe load/store functions should always be generated.
2. type-unsafe load/store functions are generated according to the pointer size.
> Minor fix of Prelude.cpp

- share/smack/top.py
This PR intends to solve the issue where SMACK leaves temporary files when it receives sigterm. We want to handle this issue because both `regtest.py` and `benchexec` use sigterm to stop processes. As a result, we had to use a script to clean these temporary files on Emulab machines.
> Remove temporary files when sigterm is received

- bin/build.sh
- lib/smack/Prelude.cpp
- share/smack/top.py
This adds basic support for CVC4. It can be used instead of Z3 by adding the flag `--verifier-options=/bopt:proverOpt:SOLVER=cvc4` when using Corral, and `--verifier-options=/proverOpt:SOLVER=cvc4` when using Boogie. Adding support for CVC4 required making the "srem" and "urem" functions uninterpreted, as CVC4 does not currently support a "rem" function for integers. Additionally, CVC4 supports "bv2nat" in place of "bv2int".
> CVC4 support

- .travis.yml
- include/smack/SmackOptions.h
- lib/smack/SmackInstGenerator.cpp
- lib/smack/SmackOptions.cpp
- share/smack/top.py
- test/special/assume.c
- test/special/assume2.c
- test/special/assume_check.c
- test/special/assume_check2.c
- test/special/assume_check_fail.c
- test/special/assume_fail.c
Currently we don't do anything with LLVM's assume statement. This is because we
need to be sure that the assumption provided to the function is correct. At best
it might help with verification, but it could also lead SMACK to report erroneous
bugs (or no bugs!). For now, this removes this intrinsic, preventing a warning about an unsound
call to this function.
I could add the closure in the stmtMap, but I think it's valuable to have the rationale somewhere in this function.
> [WIP] Optionally model the LLVM assume statement in Boogie

- include/smack/BoogieAst.h
- lib/smack/BoogieAst.cpp
- lib/smack/Prelude.cpp
- lib/smack/SmackInstGenerator.cpp
- lib/smack/SmackRep.cpp
- test/basic/select.c
- test/basic/select_fail.c
This removes the `CondExpr` class in favor of the more descriptively named `IfThenElseExpr` class. The printing of `IfThenElseExpr` now encloses the expression in parentheses to prevent precedence issues.
> Remove duplicate conditional AST node

- include/dsa/DSGraphTraits.h
This fix was [merged upstream](https://reviews.llvm.org/D54377#1298014) and (I think) released in LLVM 7.0.1.
> Remove patched `pointer_iterator`

- lib/smack/Regions.cpp
- lib/smack/SmackInstGenerator.cpp
- test/c/basic/malloc_collapsing.c
In order to establish whether a pointer returned from an external
function can alias program-allocated memory, we used to generate
regions for return values of pointer types of all functions. We
used to do that no matter how the pointers would end up being used.
In the case of malloc, this would almost always lead to collapsing
of regions since malloc returns a pointer of type i8, but is
almost always cast into the appropriate type and then used.
This fix removes this behavior and avoids collapsing of regions
due to malloc.
Fixes #473
> Fixed over-collapsing of regions when malloc is encountered

- share/smack/include/smack.h
- test/c/basic/select.c
- test/c/basic/select_fail.c
- test/c/ntdrivers/floppy2_true.i.cil.c
- test/c/special/assume.c
- test/c/special/assume2.c
- test/c/special/assume_check.c
- test/c/special/assume_check2.c
- test/c/special/assume_check_fail.c
- test/c/special/assume_fail.c
Assert was causing a compilation warning since it used to expand
into `__VERIFIER_assert` directly. This is now fixed by wrapping
it with an if condition.
> Fixed compilation warning that assert was causing

- share/smack/frontend.py
- share/smack/lib/pthread.c
Fix #520 by switching between Boogie types in `pthread.c`. Previously the file used Boogie int everywhere.
> Fix smack pthread.c when using --bit-precise

- share/smack/lib/pthread.c
- test/c/pthread/join_null_retval.c
Check for NULL retval parameter before deref
> Fix #528: memsafe pthread_join stub

- test/rust/basic/arith.rs
This PR removed the only place where `--bit-precise` is needed (also unnecessarily).
> Fix issue #498

- share/smack/lib/math.c
The type of variable `val` should be `long double`.
Fixes #558
> Fix the implementation of the `fdiml` function

- share/smack/lib/smack.rs
- test/rust/basic/print.rs
- test/rust/basic/print_fail.rs
> Change Rust print*! macros to simply evaluate the arguments

- share/smack/frontend.py
- test/rust/basic/nondet_defined.rs
This addresses an issue where Rust programs had `nondet` functions undefined. This is due to LLVM information not being present in the generated `rlib`. This addresses this by compiling `smack.rs` as a `bc` file for linking.
> Fix Rust compilation

- include/smack/MemorySafetyChecker.h
- lib/smack/MemorySafetyChecker.cpp
There is no need to cache memory safety functions on our end
since LLVM already does that for us.
> Simplified memory safety checking

- bin/build.sh
- share/smack/top.py
This commit demangles function/variable names shown in the error traces of
failing C++/Rust programs. It invokes cxxfilt and rustfilt if they are in the
PATH. It also installs rustfilt when Rust is installed.
> Demangle C++/Rust names in the error traces

- lib/smack/Prelude.cpp
- share/smack/top.py
- test/c/bits/pointers.c
- test/c/bits/pointers1.c
- test/c/bits/pointers1_fail.c
- test/c/bits/pointers_fail.c
- tools/llvm2bpl/llvm2bpl.cpp
In the previous implementation, the former flag implies the latter flag, which
seems unnecessary.
> Decouple bit-precise-pointers from bit-precise

- test/regtest.py
Specifically, commit 086b4da5680e1ce03048395dd0b94a17a17aeedc changed lines
```
if meta['skip'] == True:
continue
if meta['skip'] != False and not args.all_examples:
continue
```
into
```
if meta['skip']:
continue
if meta['skip'] and not args.all_examples:
continue
```
Apparently they are not semantically-equivalent and caused our CI to skip tests
unexpectedly.
> Fixed a non-semantically-preserving change introduced by autopep8

- .travis.yml
- test/c/basic/transform-out.c
This commit allows clang-format to still check that file.
> Turn off clang-format for a comment in test/c/basic/transform-out.c

- CMakeLists.txt
- include/smack/Naming.h
- include/smack/RustFixes.h
- lib/smack/Naming.cpp
- lib/smack/RustFixes.cpp
- lib/smack/SmackInstGenerator.cpp
- tools/llvm2bpl/llvm2bpl.cpp
- Removes the call to lang_start in the main function at the IR level
* This enables certain optimizations that are not available when rewriting
at the bpl level
- Remove lang_start functions from the IR
* This allows dead code elimination to remove some globals that slow
verification
> Update handling of Rust entry

- lib/smack/SmackInstGenerator.cpp
- lib/utils/Devirt.cpp
Inline assembly with side effects do not have functions being called values.
This triggers invalid translation by the `Devirt` pass and assertion failure in
`SmackInstGenerator`.
> Fixed invalid translation/assertion failure related to inline assembly

- lib/smack/SmackInstGenerator.cpp
We have precisely modeled them using axioms.
> Do not emit warnings about bitwise operations of bit-width 1

- include/smack/SmackRep.h
- lib/smack/IntegerOverflowChecker.cpp
- lib/smack/RewriteBitwiseOps.cpp
- lib/smack/SmackRep.cpp
- share/smack/include/smack.h
- share/smack/lib/smack.c
This commit always enables precise modeling of the overflow flag and does not
inject blocking assumes.
> Temporarily fixed LLVM intrinsics modeling

- CMakeLists.txt
- bin/build.sh
- examples/rust-cargo/Cargo.toml
- share/smack/frontend.py
- share/smack/include/smack.h
- share/smack/lib/smack-rust.c
- share/smack/lib/smack.c
- share/smack/lib/smack.rs
- share/smack/lib/smack/build.rs
- test/rust/cargo/cargo-test/Cargo.toml
This PR attempts to fix build issues when using cargo. The fixes/refactorings are,
* Split Rust's FFIs into a designated file named `smack-rust.c`. This allows us to decouple Rust-related C functions from SMACK's C libraries, which further enables uploading the SMACK crate to crates.io.
* Fix installation path issues.
* Install `Cargo.toml` and `build.rs`.
> Fixes for cargo builds

- include/smack/SmackInstGenerator.h
- include/smack/SmackWarnings.h
- lib/smack/SmackInstGenerator.cpp
- lib/smack/SmackOptions.cpp
- lib/smack/SmackRep.cpp
- lib/smack/SmackWarnings.cpp
- share/smack/top.py
This commit changes incorrectly named `warn.*Unsound` into `warnIfIncomplete` or
`warnUnModeled` to better reflect their meanings. In the meanwhile, the
incorretly named warning level `unsound` gets changed to `imprecise`.
Fixes #614
> Refactored warning message APIs

- bin/build.sh
LLVM has relocated the hosting for their source archives. This PR updates the locations in build.sh so LLVM can be built from source.
> Update LLVM source locations to use github addresses

- include/smack/Naming.h
- include/smack/SmackOptions.h
- lib/smack/AddTiming.cpp
- lib/smack/Debug.cpp
- lib/smack/IntegerOverflowChecker.cpp
- lib/smack/Naming.cpp
- lib/smack/RemoveDeadDefs.cpp
- lib/smack/RustFixes.cpp
- lib/smack/SmackInstGenerator.cpp
- lib/smack/SmackOptions.cpp
This commit also replaces some usages of std::string with
llvm::StringRef.
Partially fixes #691
> Made casts from llvm::StringRef to std::string explicit

- .github/workflows/smack-ci.yaml
- test/regtest.py
- test/rust/cargo/num-crate-test-fail/Cargo.toml
- test/rust/cargo/num-crate-test/Cargo.toml
I had to run them one by one otherwise concurrency issues of Cargo will be triggered, which leads to incorrect results.
> Add Cargo examples to regressions

- CMakeLists.txt
This commit consists of three parts.
1. Fixed style warnings reported by cmakelint
2. Removed stale compilation flag manipulations.
3. Justifed remaining flag manipulations.
Closes #532
> Updated CMakeLists.txt

- .github/workflows/smack-ci.yaml
- include/smack/SmackOptions.h
- lib/smack/IntegerOverflowChecker.cpp
- lib/smack/MemorySafetyChecker.cpp
- lib/smack/SmackInstGenerator.cpp
- lib/smack/SmackOptions.cpp
- share/smack/top.py
- test/c/targeted-checks/targeted_assertion.c
- test/c/targeted-checks/targeted_assertion_fail.c
- test/c/targeted-checks/targeted_assume_checking.c
- test/c/targeted-checks/targeted_assume_checking_fail.c
- test/c/targeted-checks/targeted_memory_safety.c
- test/c/targeted-checks/targeted_memory_safety_fail.c
- test/c/targeted-checks/targeted_overflow_arithmetic.c
- test/c/targeted-checks/targeted_overflow_arithmetic_fail.c
- test/c/targeted-checks/targeted_overflow_shift.c
- test/c/targeted-checks/targeted_overflow_shift_fail.c
- test/c/targeted-checks/test-match.c
- test/c/targeted-checks/test-match_fail1.c
- test/c/targeted-checks/test-match_fail2.c
- test/c/targeted-checks/test-match_fail3.c
- test/rust/targeted-checks/targeted_panic.rs
- test/rust/targeted-checks/targeted_panic2.rs
- test/rust/targeted-checks/targeted_panic2_fail.rs
- test/rust/targeted-checks/targeted_panic_fail.rs
This adds the ability to selectively check certain functions in a program, specifically:
* This adds the option `--checked-functions' which is a list of functions
on which to do checking
* Not specifying this option enables all checks in every function
This partially addresses #713
> Add an option to enable targeted checking of specific functions

- bin/build.sh
This PR does the following:
* All installation flags can now be provided through the environment, enabling control over what is installed
* Added the `INSTALL_LLVM` flag (default enabled) to control whether we install LLVM. This is for situations where a user already has an appropriate installation
* Fix the `PATH` environment variable when doing a prefix build so that it doesn't copy the path from the build environment.
> Enable control of build.sh installation instructions via the environment

- share/smack/svcomp/utils.py
- share/smack/top.py
Previously, SMACK doesn't report the error type such as ``invalid pointer
dereference'' when Boogie is used. This commit fixes it. Furthermore, the
original error type generation for Corral is also improved.
> Generate precise error type when Boogie is used

- share/smack/frontend.py
- share/smack/top.py
- share/smack/utils.py
This PR makes our usage of LLVM's command line utilities more consistent by making `llvm-dis` use the Smack installed version of the LLVM package.
> Make llvm-dis use LLVM short version in top.py
